figure out where secret is7

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -64,9 +64,10 @@ jobs:
 
       - name: Run TruffleHog scan
         run: |
+          # Run but don’t fail the job
           trufflehog git file://. --json --no-verification \
             --base ${{ github.event.repository.default_branch }} \
-            --head HEAD > trufflehog_results.json
+            --head HEAD > trufflehog_results.json || true
 
       - name: Show Unverified Secrets Only
         run: |
